name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 1.9.5+3
homepage: https://github.com/mmcc007/tool_base
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: ^3.3.5
  file: ^6.1.2
  platform: ^3.1.0
  process: ^4.2.4
  pub_cache: ^0.3.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^5.3.2
  quiver: ^3.2.1
  file_testing: ^3.0.0
